### ISSUE TITLE
bar 100% of monitor

### ISSUE THREAD

**Issue by syswombat** [roddhjav/progressbar#2]
hello

would be nice to have the bar 100% of the Monitor.

and would be nice if i could call up the bar
progressbar.sh 120

an not to use this
```
#!/bin/bash

# Loading progressbar
source progressbar.sh || exit 1

start=0
end=25
for ii in $(seq $start $end); do
    sleep 0.1
    progressbar "My progress bar" $ii $end
done
echo
```

for 120 Second to count down.

have a nice day
vinc

**Comment by roddhjav** [comment]
Hi,

> have the bar 100% of the Monitor.

What do you mean exactly? 

> would be nice if i could call up the bar
progressbar.sh 120

That does not make sense, in a application instead of `sleep 0.1` you would put the code of something you need to do a bit of time and for what you want a progress bar. So they should always be a loop and call `progressbar` in it.
